### ISSUE TITLE
Link User Stories with Commits

### ISSUE THREAD

**Issue by KarrieCheng** [MitchellBarker/fork-friendly#1]
Mitch, since you're the owner of the repository, could you do this?
http://www.pivotaltracker.com/community/tracker-blog/guide-githubs-service-hook-tracker

**Comment by MitchellBarker** [comment]
Yeah but could you do steps 1 and 2. I tried but I don't think I can make a user there. I think we should make a user called auto-delivery like they suggest.

-Mitchell Barker

On Mar 9, 2016, at 05:12, Karrie Cheng <notifications@github.com<mailto:notifications@github.com>> wrote:

Mitch, since you're the owner of the repository, could you do this?
http://www.pivotaltracker.com/community/tracker-blog/guide-githubs-service-hook-tracker

##

**Comment by bluyam** [comment]
@KarrieCheng bump
